dependencies:
  - name: rabbitmq-ha
    version: ^0.1.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: rabbitmq-ha.enabled
  - name: nginx-ingress
    version: ^0.8.11
    repository: https://kubernetes-charts.storage.googleapis.com