replicaCount: 1
image:
  repository: activiti/activiti-cloud-registry
  tag: latest
  pullPolicy: Always
service:
  name: activiti-cloud-registry
  externalPort: 8761
  internalPort: 8761
  type: ClusterIP
ingress:
  path: /registry/*