rabbitmq-ha:
  enabled: true
  rbac:
    create: false
  persistence:
    enabled: false
    size: 10Gi

activemq:
  image:
    repository: webcenter/activemq
    tag: latest
    pullPolicy: Always
    configMinMemory: "512"
    configMaxMemory: "2048"
  service:
    name: activemq
    type: ClusterIP
  serviceadmin:
    name: activemq-admin
    type: NodePort
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "2048Mi"
  broker:
    ports:
      amqp: 5672
      openwire: 61616
  monitor:
    ports:
      monitor: 8161

persistence:
  enabled: false
  size: 3Gi
  volumeEnv: minikube #Choose between aws and minikube
  nfs:
    server: fs-6570472c.efs.us-east-1.amazonaws.com #For aws you will need to specify the EFS server