{{- if and .Values.persistence.efs.enabled (not .Values.persistence.existingVolume) -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alfresco-volume
spec:
  capacity:
    storage: {{ .Values.persistence.baseSize | quote }}
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  nfs:
    server: "{{ .Values.persistence.efs.dns }}"
    path: "{{ .Values.persistence.efs.path }}"
  storageClassName: efs
---
{{- end -}}
