{{- if and .Values.persistence.efs.enabled (not .Values.persistence.existingVolume) -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs
provisioner: alfresco.com/efs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alfresco-volume
spec:
  capacity:
    storage: {{ .Values.persistence.baseSize | quote }}
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  nfs:
    server: "{{ .Values.persistence.efs.dns }}"
    path: "{{ .Values.persistence.efs.path }}"
  storageClassName: efs
---
{{- end -}}
