apiVersion: v1
description: A Helm chart Providing the required Alfresco infrastructure. This includes nginx-ingress, activemq, alfresco-api-gateway, alfresco-identity-service, and the content services volume.
name: alfresco-infrastructure
version: 1.0.0
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4