apiVersion: v1
description: A Helm chart Providing the required Alfresco infrastructure for the Digital Business Platform.
name: alfresco-infrastructure
version: 1.1.0-SNAPSHOT
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
