persistence:
  enabled: true
  baseSize: 20Gi
  storageClass: #enable and define if you already have a custom storage class defined
    enabled: false
    accessModes:
      - ReadWriteMany
    name: "nfs-client" #Custom storage classs name

nginx-ingress:
  rbac:
    create: true
  controller:
    scope:
      enabled: true  
    config:
      ssl-redirect: "false"
      server-tokens: "false"
 
alfresco-infrastructure:
  alfresco-identity-service:
    enabled: true
  activemq:
    enabled: true
  alfresco-event-gateway:
    enabled: true
  nginx-ingress:
    enabled: true
