persistence:
  enabled: true
  efs:
    enabled: false
    dns: fs-example.efs.us-east-1.amazonaws.com #For aws you will need to specify the EFS server
    path: "/"
  baseSize: 20Gi

nginx-ingress:
  rbac:
    create: true
  controller:
    scope:
      enabled: true  
    config:
      ssl-redirect: "false"
      server-tokens: "false"

alfresco-infrastructure:
  activemq:
    enabled: true
  alfresco-identity-service:
    enabled: true