
persistence:
  enabled: true
  baseSize: 20Gi
  efs:
    enabled: false
    dns: fs-example.efs.us-east-1.amazonaws.com #For aws you will need to specify the EFS server
    path: "/"
  azureFile:
    enabled: false
    secretName: ""
    shareName: ""
    # In case the secret is stored in a different namespace
    shareNamespace: ""

activemq:
  enabled: true
  
nginx-ingress:
  rbac:
    create: true
  controller:
    scope:
      enabled: true  
    config:
      ssl-redirect: "false"

alfresco-identity-service:
  enabled: true