apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "dbp-infrastructure.fullname" . }}-activemq
  labels:
    app: {{ template "dbp-infrastructure.fullname" . }}-activemq
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "dbp-infrastructure.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: activemq
        image: "{{ .Values.activemq.image.repository }}:{{ .Values.activemq.image.tag }}"
        imagePullPolicy: {{ .Values.activemq.image.pullPolicy }}
        env:
        - name: ACTIVEMQ_CONFIG_MINMEMORY
          value: "{{ .Values.activemq.image.configMinMemory }}"
        - name: ACTIVEMQ_CONFIG_MAXMEMORY
          value: "{{ .Values.activemq.image.configMaxMemory }}"
        ports:
        - name: broker
          containerPort: {{ .Values.activemq.broker.ports.openwire | default 61616 }}
        - name: amqp
          containerPort: {{ .Values.activemq.broker.ports.amqp | default 5672 }}
        - name: monitor
          containerPort: {{ .Values.activemq.monitor.ports.monitor | default 8161 }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.activemq.monitor.ports.monitor | default 8161 }}
          initialDelaySeconds: 5
          periodSeconds: 25
        resources:
{{ toYaml .Values.activemq.resources | indent 12 }}
