{{- if .Values.persistence.enabled -}}
{{- if .Values.persistence.efs.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ template "alfresco-infrastructure.fullname" . }}
provisioner: alfresco.com/pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ template "alfresco-infrastructure.fullname" . }}
spec:
  capacity:
    storage: {{ .Values.persistence.baseSize | quote }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy | default "Recycle" }}
  nfs:
    server: "{{ .Values.persistence.efs.dns }}"
    path: "{{ .Values.persistence.efs.path }}"
  storageClassName: {{ template "alfresco-infrastructure.fullname" . }}
---
{{- end }}
{{- if .Values.persistence.azureFile.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ template "alfresco-infrastructure.fullname" . }}
provisioner: alfresco.com/pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ template "alfresco-infrastructure.fullname" . }}
spec:
  capacity:
    storage: {{ .Values.persistence.baseSize | quote }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy | default "Recycle" }}
  azureFile:
    secretName: {{ .Values.persistence.azureFile.secretName }}
    shareName:  {{ .Values.persistence.azureFile.shareName }}
    # In case the secret is stored in a different namespace
    shareNamespace: {{ .Values.persistence.azureFile.shareNamespace | default .Release.Namespace }}
    readOnly: false
  storageClassName: {{ template "alfresco-infrastructure.fullname" . }}
---
{{- end }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alfresco-volume-claim
spec:
  accessModes:
  {{ if or .Values.persistence.efs.enabled .Values.persistence.azureFile.enabled }}
    - ReadWriteMany
  storageClassName: {{ template "alfresco-infrastructure.fullname" . }}
  {{ else }}
    - ReadWriteOnce
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.persistence.baseSize | quote }}
{{- end -}}